### ISSUE TITLE
AGASC supplement processing failing

### ISSUE THREAD

**Issue by taldcroft** [sot/agasc#149]
The current processing seems to be failing.
```
WARNING - 'agasc-update-magnitudes --log-level debug --output-dir /proj/sot/ska3/flight/data/agasc/rc --report' returned non-zero status: 256
2023-04-16 18:30:28,496   identifying outlying observations (OBSID=17898, mp_starcat_time=2016:088:21:54:47.566)
2023-04-16 18:30:28,496   identifying outlying observations (OBSID=18808, mp_starcat_time=2016:091:10:07:50.653)
2023-04-16 18:30:28,497   identifying outlying observations (OBSID=17899, mp_starcat_time=2016:263:06:32:39.175)
2023-04-16 18:30:28,497   identifying outlying observations (OBSID=19882, mp_starcat_time=2016:267:11:11:40.571)
2023-04-16 18:30:28,498   identifying outlying observations (OBSID=50688, mp_starcat_time=2016:267:23:55:18.419)
2023-04-16 18:30:28,498   identifying outlying observations (OBSID=20036, mp_starcat_time=2017:072:22:54:05.330)
2023-04-16 18:30:28,499   identifying outlying observations (OBSID=19290, mp_starcat_time=2017:075:04:07:33.998)
2023-04-16 18:30:28,499   identifying outlying observations (OBSID=19289, mp_starcat_time=2017:266:15:19:04.302)
2023-04-16 18:30:28,500   identifying outlying observations (OBSID=20927, mp_starcat_time=2018:072:23:50:12.293)
2023-04-16 18:30:28,500   identifying outlying observations (OBSID=21037, mp_starcat_time=2018:074:09:52:55.134)
2023-04-16 18:30:28,500   identifying outlying observations (OBSID=21038, mp_starcat_time=2018:077:23:34:33.598)
2023-04-16 18:30:28,501   identifying outlying observations (OBSID=20322, mp_starcat_time=2018:078:21:24:04.027)
2023-04-16 18:30:28,501   identifying outlying observations (OBSID=21042, mp_starcat_time=2018:082:08:20:45.650)
2023-04-16 18:30:28,502   identifying outlying observations (OBSID=21043, mp_starcat_time=2018:083:23:57:28.826)
2023-04-16 18:30:28,502   identifying outlying observations (OBSID=21044, mp_starcat_time=2018:085:05:10:15.300)
2023-04-16 18:30:28,503   identifying outlying observations (OBSID=21303, mp_starcat_time=2019:078:09:38:22.468)
2023-04-16 18:30:28,503   identifying outlying observations (OBSID=22155, mp_starcat_time=2019:082:14:26:23.212)
2023-04-16 18:30:28,503   identifying outlying observations (OBSID=22156, mp_starcat_time=2019:083:06:52:17.168)
2023-04-16 18:30:28,504   identifying outlying observations (OBSID=22424, mp_starcat_time=2020:083:20:19:57.416)
2023-04-16 18:30:28,504   identifying outlying observations (OBSID=23198, mp_starcat_time=2020:088:12:38:04.723)
2023-04-16 18:30:28,505   identifying outlying observations (OBSID=22425, mp_starcat_time=2020:256:19:09:07.110)
2023-04-16 18:30:28,505   identifying outlying observations (OBSID=24652, mp_starcat_time=2020:261:02:05:00.282)
2023-04-16 18:30:28,506   identifying outlying observations (OBSID=23533, mp_starcat_time=2021:084:18:14:42.948)
2023-04-16 18:30:28,506   identifying outlying observations (OBSID=22703, mp_starcat_time=2021:090:00:23:53.876)
2023-04-16 18:30:28,506   identifying outlying observations (OBSID=23534, mp_starcat_time=2021:298:20:16:23.403)
2023-04-16 18:30:28,507   identifying outlying observations (OBSID=24295, mp_starcat_time=2021:300:15:22:55.780)
2023-04-16 18:30:28,507   identifying outlying observations (OBSID=24654, mp_starcat_time=2021:301:03:51:55.265)
2023-04-16 18:30:28,508   identifying outlying observations (OBSID=27443, mp_starcat_time=2022:263:16:59:47.126)
2023-04-16 18:30:28,508   identifying outlying observations (OBSID=25514, mp_starcat_time=2022:264:03:11:27.974)
2023-04-16 18:30:28,508   identifying outlying observations (OBSID=25906, mp_starcat_time=2022:270:13:37:13.779)
2023-04-16 18:30:28,509   identifying outlying observations (OBSID=27605, mp_starcat_time=2022:351:20:02:02.217)
2023-04-16 18:30:28,509   identifying outlying observations (OBSID=27606, mp_starcat_time=2022:352:02:51:41.560)
2023-04-16 18:30:28,510   identifying outlying observations (OBSID=25511, mp_starcat_time=2023:103:19:12:20.573)
2023-04-16 18:30:32,108   stats for AGASC ID 1201542672:  8.178614346046494

progress: 100%|██████████| 228/228 [38:47<00:00, 10.21s/star]
2023-04-16 18:30:32,109 --------------------------------------------------------------------------------
2023-04-16 18:30:32,730 Got:
  2952 OBSIDs,  228 stars,  2 failed observations,
2023-04-16 18:30:32,731 Updating /proj/sot/ska3/flight/data/agasc/rc/mag_stats_agasc.fits
Traceback (most recent call last):
  File "/proj/sot/ska3/flight/bin/agasc-update-magnitudes", line 33, in <module>
    sys.exit(load_entry_point('agasc==4.14.1', 'console_scripts', 'agasc-update-magnitudes')())
  File "/proj/sot/ska3/flight/lib/python3.10/site-packages/agasc/scripts/update_mag_supplement.py", line 158, in main
    update_mag_supplement.do(
  File "/proj/sot/ska3/flight/lib/python3.10/site-packages/agasc/supplement/magnitudes/update_mag_supplement.py", line 572, in do
    update_mag_stats(obs_stats, agasc_stats, fails, output_dir)
  File "/proj/sot/ska3/flight/lib/python3.10/site-packages/agasc/supplement/magnitudes/update_mag_supplement.py", line 207, in update_mag_stats
    agasc_stats = _update_table(table.Table.read(filename), agasc_stats,
  File "/proj/sot/ska3/flight/lib/python3.10/site-packages/agasc/supplement/magnitudes/update_mag_supplement.py", line 176, in _update_table
    assert table_old.as_array().dtype.names == table_new.as_array().dtype.names, \
AssertionError: Tables have different dtype
```

**Comment by javierggt** [comment]
I was just able to reproduce this error using the following command:
```
python -m agasc.scripts.update_mag_supplement --log-level debug --output-dir /proj/sot/ska/jgonzalez/agasc/error-April-2023 --report --agasc-id-file agasc_ids
```
where the `agasc_ids` file contains the following:
```
38016952
44833528
44966344
```
The error happens because (for reasons yet to be determined) the columns of the `agasc_stats` table on file and the columns of the `agasc_stats` table in memory are in different order. The first star in the list fails, and if I remove it from the file, then the error does not occur.

**Why might this happen**

I think the key is that the **first** observation fails.  The return value of `mag_estimate.get_obs_stats` and `mag_estimate.get_agasc_id_stats` is a dictionary. These functions first create a dictionary with default values, and then they are updated as the function proceeds. If something fails, the function exits. I am guessing that the order of the keys in the dictionary will depend on where the function exits (i.e. on the sequence of updates).  Then `astropy.Table` might use the first entry to set the dtype (or at least the column order). This means that the resulting table is different if the first observation fails, which is not common. 

**A possible solution**

I changed my local copy so it checks that the *set* of columns are the same, and makes sure to reorder columns in the new table.

**Another error**

After fixing this error, there is a new error :
```
Error when creating report: keys must be str, int, float, bool or None, not int64
```
this error is independent, but also does not happen when the failing observation is not included. It happens when dumping the star report in JSON at the very end, **after** saving the html. As a result, the html report is produced, but the symlink is not updated. I will investigate this further and create a PR.
