### ISSUE TITLE
agasc test failed then passed

### ISSUE THREAD

**Issue by jeanconn** [sot/agasc#17]
Not sure where to stick this issue, but when running ska_testr today, the agasc tests had a failure.  But when I reran the tests the failure went away.  Wondering if a test needs to be tweaked to be more .. deterministic.

```

Copying input tests packages/agasc to output dir outputs/3.18-r744-aa8e056_x86_64_fido/agasc
Running python test_unit.py script
Bash-12:46:21> export TESTR_FILE='test_unit.py'
Bash-12:46:21> export TESTR_STATUS='not run'
Bash-12:46:21> export TESTR_INTERPRETER='python'
Bash-12:46:21> export TESTR_OUT_DIR='/proj/sot/ska/jeanproj/git/ska_testr/outputs/3.18-r744-aa8e056_x86_64_fido/agasc'
Bash-12:46:21> export TESTR_REGRESS_DIR='/proj/sot/ska/jeanproj/git/ska_testr/regress/HEAD_PY3/3.18-r744-aa8e056_x86_64_fido/agasc'
Bash-12:46:21> export TESTR_PACKAGES_REPO='https://github.com/sot'
Bash-12:46:21> export TESTR_PACKAGE='agasc'
Bash-12:46:21> python test_unit.py
============================= test session starts ==============================
platform linux -- Python 3.6.2, pytest-3.2.1, py-1.4.34, pluggy-0.4.0 -- /proj/sot/ska3/test_centos5/arch/x86_64-linux_CentOS-6/bin/python
cachedir: .cache
rootdir: /proj/sot/ska3/test_centos5/arch/x86_64-linux_CentOS-5/lib/python3.6/site-packages, inifile:
collected 14 items                                                              

agasc/tests/test_agasc_1.py::test_multi_agasc PASSED
agasc/tests/test_agasc_2.py::test_agasc_conesearch[44.4770994823-58.9200675029] PASSED
agasc/tests/test_agasc_2.py::test_agasc_conesearch[332.019791099-22.3503622035] Bad star 288754848 1.35675678161 11.365000267 True
FAILED
agasc/tests/test_agasc_2.py::test_agasc_conesearch[0.0-89.9] PASSED
agasc/tests/test_agasc_2.py::test_agasc_conesearch[180.0--89.9] PASSED
agasc/tests/test_agasc_2.py::test_agasc_conesearch[0.1-0.0] PASSED
agasc/tests/test_agasc_2.py::test_agasc_conesearch[180.0-0.0] PASSED
agasc/tests/test_agasc_2.py::test_agasc_conesearch[275.364764174-8.09998416453] PASSED
agasc/tests/test_agasc_2.py::test_basic PASSED
agasc/tests/test_agasc_2.py::test_proper_motion PASSED
agasc/tests/test_agasc_2.py::test_add_pmcorr_is_consistent[1180612288-2020:001-219.86433151831795--60.83186800722129-high proper motion, epoch 2000] PASSED
agasc/tests/test_agasc_2.py::test_add_pmcorr_is_consistent[198451217-2020:001-247.89220668106938-19.27660555555556-epoch 1982 star] PASSED
agasc/tests/test_agasc_2.py::test_add_pmcorr_is_consistent[501219465-2020:001-166.99897608782592-52.82208000152103-epoch 1984 star] PASSED
agasc/tests/test_agasc_2.py::test_agasc_id ra, dec = 214.476578388 -4.93400650932
  agasc_id = 652615808
  agasc_id = 652616464
  agasc_id = 652616816
  agasc_id = 652617232
  agasc_id = 653009040
ra, dec = 191.469734559 23.8158498927
  agasc_id = 260836600
  agasc_id = 260840544
  agasc_id = 260846536
  agasc_id = 260851656
  agasc_id = 260852448
PASSED

=================================== FAILURES ===================================
______________ test_agasc_conesearch[332.019791099-22.3503622035] ______________

ra = 332.01979109911042, dec = 22.35036220351747

    @pytest.mark.skipif('ascds_env is None')
    @pytest.mark.parametrize("ra,dec", list(zip(ras, decs)))
    def test_agasc_conesearch(ra, dec):
>       _test_agasc(ra, dec)

agasc/tests/test_agasc_2.py:138: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

ra = 332.01979109911042, dec = 22.35036220351747, radius = 1.4
agasc_file = None

    def _test_agasc(ra, dec, radius=1.4, agasc_file=None):
        stars1 = agasc.get_agasc_cone(ra, dec, radius=radius, agasc_file=agasc_file,
                                      date='2000:001')
        stars1.sort('AGASC_ID')
    
        stars2 = mp_get_agasc(ra, dec, radius)
        stars2.sort('AGASC_ID')
    
        # First make sure that the common stars are identical
        agasc_ids = set(stars1['AGASC_ID']).intersection(set(stars2['AGASC_ID']))
        for agasc_id in agasc_ids:
            star1 = stars1[np.searchsorted(stars1['AGASC_ID'], agasc_id)]
            star2 = stars2[np.searchsorted(stars2['AGASC_ID'], agasc_id)]
            for colname in AGASC_COLNAMES:
                if star1[colname].dtype.kind == 'f':
                    assert np.all(np.abs(star1[colname] - star2[colname]) < 1e-4)
                else:
                    assert star1[colname] == star2[colname]
    
        # Second make sure that the non-common stars are all just at the edge
        # of the faint mag limit, due to precision loss in mp_get_agasc
        for s1, s2 in ((stars1, stars2),
                       (stars2, stars1)):
            mm1 = set(s1['AGASC_ID']) - set(s2['AGASC_ID'])
            for agasc_id in mm1:
                idx = np.flatnonzero(s1['AGASC_ID'] == agasc_id)[0]
                star = s1[idx]
                bad_is_star1 = s1 is stars1
                rad = agasc.sphere_dist(ra, dec, star['RA'], star['DEC'])
                adj_mag = star['MAG_ACA'] - 3.0 * star['MAG_ACA_ERR'] / 100.0
                if adj_mag < 11.5 * 0.99:
                    # Allow for loss of precision in output of mp_get_agasc
                    print('Bad star', agasc_id, rad, adj_mag, bad_is_star1)
>                   assert False
E                   assert False

agasc/tests/test_agasc_2.py:174: AssertionError
===================== 1 failed, 13 passed in 70.74 seconds =====================
Traceback (most recent call last):
  File "test_unit.py", line 2, in <module>
    testr.testr()
  File "/proj/sot/ska3/test_centos5/arch/x86_64-linux_CentOS-6/lib/python3.6/site-packages/testr/runner.py", line 35, in testr
    return test(*args, **kwargs)
  File "/proj/sot/ska3/test_centos5/arch/x86_64-linux_CentOS-6/lib/python3.6/site-packages/testr/runner.py", line 120, in test
    raise TestError('got {} failure(s)'.format(n_fail))
testr.runner.TestError: got 1 failure(s)
Bash-12:47:36> Running python post_check_logs.py script
Bash-12:47:36> export TESTR_FILE='post_check_logs.py'
Bash-12:47:36> export TESTR_STATUS='not run'
Bash-12:47:36> export TESTR_INTERPRETER='python'
Bash-12:47:36> export TESTR_OUT_DIR='/proj/sot/ska/jeanproj/git/ska_testr/outputs/3.18-r744-aa8e056_x86_64_fido/agasc'
Bash-12:47:36> export TESTR_REGRESS_DIR='/proj/sot/ska/jeanproj/git/ska_testr/regress/HEAD_PY3/3.18-r744-aa8e056_x86_64_fido/agasc'
Bash-12:47:36> export TESTR_PACKAGES_REPO='https://github.com/sot'
Bash-12:47:36> export TESTR_PACKAGE='agasc'
Bash-12:47:36> python post_check_logs.py
Traceback (most recent call last):
  File "post_check_logs.py", line 3, in <module>
    check_files('test_*.log', ['warning', 'error'])
  File "/proj/sot/ska3/test_centos5/arch/x86_64-linux_CentOS-6/lib/python3.6/site-packages/testr/packages.py", line 322, in check_files
    raise ValueError('Found matches in check_files:\n{}'.format('\n'.join(matches)))
ValueError: Found matches in check_files:
'error' matched at test_unit.py.log:98 :: agasc/tests/test_agasc_2.py:174: AssertionError
'error' matched at test_unit.py.log:106 :: raise TestError('got {} failure(s)'.format(n_fail))
'error' matched at test_unit.py.log:107 :: testr.runner.TestError: got 1 failure(s)
Bash-12:47:40> ****************************************
*** agasc Test Summary               ***
*** test_unit.py         FAIL        ***
*** post_check_logs.py   FAIL        ***
****************************************
```

**Comment by javierggt** [comment]
Do we need to keep this issue open?

**Comment by jeanconn** [comment]
No.  It is vintage and the bug report doesn't contribute anything useful.  Closing as OBE
