### ISSUE TITLE
bug on file_args in update_mag_supplement

### ISSUE THREAD

**Issue by jeanconn** [sot/agasc#176]
```
WARNING - 'agasc-update-magnitudes --log-level debug --output-dir /proj/sot/ska3/flight/data/agasc/rc --report' returned non-zero status: 256
Traceback (most recent call last):
  File "/proj/sot/ska3/flight/bin/agasc-update-magnitudes", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/proj/sot/ska3/flight/lib/python3.11/site-packages/agasc/scripts/update_mag_supplement.py", line 249, in main
    args = get_args()
           ^^^^^^^^^^
  File "/proj/sot/ska3/flight/lib/python3.11/site-packages/agasc/scripts/update_mag_supplement.py", line 166, in get_args
    if "agasc_ids" in file_args:
                      ^^^^^^^^^
UnboundLocalError: cannot access local variable 'file_args' where it is not associated with a value
```

**Comment by jeanconn** [comment]
I think this was a tiny bug introduced in https://github.com/sot/agasc/pull/168 .
