### ISSUE TITLE
Trouble installing in new ska on non-networked system

### ISSUE THREAD

**Issue by jeanconn** [sot/agasc#21]
It looks like the install tries to import the module to get a version and the lines that effect

```
DATA_ROOT = ska_path('data', 'agasc')
DEFAULT_AGASC_FILE = os.path.join(DATA_ROOT, 'miniagasc.h5')
```

break. Should I make a change in ska_path or in agasc to handle the case of a brand new ska (no data directory yet)?

```    
default: Processing /proj/jwst/build/x86_64-linux_CentOS-7/agasc-3.5.2
    default:   Running setup.py (path:/tmp/pip-r7zm_u9j-build/setup.py) egg_info for package from file:///proj/jwst/build/x86_64-linux_CentOS-7/agasc-3.5.2
    default:     Running command python setup.py egg_info
    default:     Traceback (most recent call last):
    default:       File "<string>", line 1, in <module>
    default:       File "/tmp/pip-r7zm_u9j-build/setup.py", line 4, in <module>
    default:         from agasc import __version__
    default:       File "/tmp/pip-r7zm_u9j-build/agasc/__init__.py", line 2, in <module>
    default:         from .agasc import *
    default:       File "/tmp/pip-r7zm_u9j-build/agasc/agasc.py", line 18, in <module>
    default:         DEFAULT_AGASC_FILE = os.path.join(DATA_ROOT, 'miniagasc.h5')
    default:       File "/proj/jwst/arch/x86_64-linux_CentOS-7/lib/python3.6/posixpath.py", line 78, in join
    default:         a = os.fspath(a)
    default:     TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by taldcroft** [comment]
`ska_path` is doing the correct thing of returning `None` in this case.  You could change the AGASC code to do:
```
DEFAULT_AGASC_FILE = os.path.join(DATA_ROOT or '', 'miniagasc.h5')
```

**Comment by jeanconn** [comment]
Closing as OBE
