### ISSUE TITLE
Command line arg types should be specified or coerced during parsing

### ISSUE THREAD

**Issue by taldcroft** [sot/agasc#79]
Some of the command line arguments are left as strings, leading to unexpected behavior like below where `agasc_id` and `obsid` are shown in logging as string values. Arguments should be either `None` or the correct type at the point of arg parsing.
```
(ska3-agasc) ➜  agasc git:(logging) python -m agasc.scripts.update_obs_status --obsid 46686 --agasc-id=175379112 --status=bad --comments="ACA high background event"
2021-02-01 06:15:21,080 updating "obs" table in agasc_supplement.h5
2021-02-01 06:15:21,080 Appending agasc_id='175379112', obsid='46686', status={'ok': 0, 'comments': 'ACA high background event'}
```

**Comment by javierggt** [comment]
I do not understand this comment. In my local version this is what I see:
```
javierg test $ agasc-supplement-obs-status --obsid 46686 --agasc-id=175379112 --status=bad --comments="ACA high background event"
2021-02-01 08:09:22,873 updating "obs" table in agasc_supplement.h5
2021-02-01 08:09:22,873 Appending agasc_id='175379112', obsid='46686', status={'status': 1, 'comments': 'ACA high background event'}
```

(`ok` was replaced by `status`).

**Comment by javierggt** [comment]
but of course, this is after PR #60.

Even on the trunk, I do not understand. The status in this context is `{'ok': 0, 'comments': 'ACA high background event'}`

**Comment by javierggt** [comment]
Just for the record... I committed a fix for this issue. The changed was based on a more recent version. In this more recent version, the output had changed, and this script was failing with the following error (but the issue was the same anyway):
```
/Users/javierg/SAO/miniconda3-shiny/envs/ska3-matlab-2021.3/lib/python3.8/site-packages/astropy/table/column.py:1152: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  result = getattr(super(), op)(other)
Traceback (most recent call last):
  File "/Users/javierg/SAO/miniconda3-shiny/envs/ska3-matlab-2021.3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/javierg/SAO/miniconda3-shiny/envs/ska3-matlab-2021.3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/javierg/SAO/git/agasc/agasc/scripts/update_supplement.py", line 280, in <module>
    main()
  File "/Users/javierg/SAO/git/agasc/agasc/scripts/update_supplement.py", line 276, in main
    update(args)
  File "/Users/javierg/SAO/git/agasc/agasc/scripts/update_supplement.py", line 228, in update
    status = parse_args(
  File "/Users/javierg/SAO/git/agasc/agasc/scripts/update_supplement.py", line 163, in parse_args
    status = _sanitize_args(status)
  File "/Users/javierg/SAO/git/agasc/agasc/scripts/update_supplement.py", line 92, in _sanitize_args
    if rows['obsid'][0] != value['obsid']:
IndexError: invalid index to scalar variable.
```

The `FutureWarning` referenced here was due to this comparison `cat.STARS_OBS['obsid'] == value['obsid']`, where `value['obsid']` was a string instead of an int. After the change, the script runs.
